build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21
  armhf: ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.21
codenotary: 
  signer: big.dog@gmx.net
  base_image: notary@home-assistant.io
